---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: heading
  label: Modify pages contents here
- type: jekyll-pages
  label: Pages
  create: documents
- type: heading
  label: Add News, Events & Success stories here
- type: directory
  path: _events
  label: Events
  create: all
  match: "**/*"
  templates:
  - event
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - blog-post
- type: directory
  path: _stories
  label: Success stories
  create: all
  match: "**/*"
  templates:
  - story
- type: heading
  label: FAQ (Add questions and answers here)
- type: directory
  path: _faqs
  label: Q&As
  create: all
  match: "**/*"
  templates:
  - faq
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
