---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: heading
  label: Add indicators here
- type: directory
  path: _indicators
  label: Indicators
  create: all
  match: "**/*"
  templates:
  - indicator
- type: heading
  label: Add Press Releases & Publications here
- type: directory
  path: _preleases
  label: Press releases
  create: all
  match: "**/*"
  templates:
  - press-release
- type: directory
  path: _publications
  label: Publications
  create: all
  match: "**/*"
  templates:
  - publication
- type: heading
  label: Add News, Events & Success stories here
- type: directory
  path: _events
  label: Events
  create: all
  match: "**/*"
  templates:
  - event
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - blog-post
- type: directory
  path: _stories
  label: Success stories
  create: all
  match: "**/*"
  templates:
  - story
- type: heading
  label: Add job positions, team members and donors here
- type: directory
  path: _jobs
  label: Job positions
  create: all
  match: "**/*"
  templates:
  - job-position
- type: directory
  path: _teams
  label: Team members
  create: all
  match: "**/*"
  templates:
  - team-member
- type: directory
  path: _donors
  label: Donors and partners
  create: all
  match: "**/*"
  templates:
  - donors-and-partners
- type: heading
  label: FAQ (Add questions and answers here)
- type: directory
  path: _faqs
  label: Q&As
  create: all
  match: "**/*"
  templates:
  - faq
- type: heading
  label: Modify pages contents here
- type: jekyll-pages
  label: Pages
  create: documents
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
